project:
  type: website

website:
  title: "sciml_quarto_test"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "GPUS"
        href: gpus/index.qmd
      - text: "Events"
        href: pages/events.md
      - about.qmd 
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css
execute:
  freeze: auto


